bullseyeScheduler/config/routes.rb
Rails.application.routes.draw do

  resources :shifts do
		get 'takeShifts' => 'shifts#takeShift'
	end  
  resources :users do
		get '/home/:location' => 'users#homestore'
		get '/setstore' => 'users#sethomestore'
	end 
  root 'static_pages#index'

	get 'tracking/hours'
  get 'static_pages/index'
  get 'static_pages/openShifts'
  get 'static_pages/about'
  get 'static_pages/contact'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

bullseyeScheduler/app/models/role.rb
class Role < ActiveRecord::Base
	has_many :user


end

bullseyeScheduler/app/models/shift.rb
class Shift < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :store_id
	STATUS = [
	"General",
	"Finalized",
	"Open",
	"Pending",
	"Closed"
	]



end

bullseyeScheduler/app/models/user.rb
class User < ActiveRecord::Base
	has_many :shift
	belongs_to :role
	before_create :set_role

  has_secure_password
	validates_uniqueness_of :email
	validates_presence_of	:home_store_id
	#State Locations
	LOCATIONS = [
		"AL",
		"AK",
		"AZ",
		"AR",
		"CA",
		"CO",
		"CT",
		"DE",
		"FL",
		"GA",
		"HI",
		"ID",
		"IL",
		"IN",
		"IA",
		"KS",
		"KY",
		"LA",
		"ME",
		"MD",
		"MA",
		"MI",
		"MN",
		"MS",
		"MO",
		"MT",
		"NE",
		"NV",
		"NH",
		"NJ",
		"NM",
		"NY",
		"NC",
		"ND",
		"OH",
		"OK",
		"OR",
		"PA",
		"RI",
		"SC",
		"SD",
		"TN",
		"TX",
		"UT",
		"VT",
		"VA",
		"WA",
		"WV",
		"WI",
		"WY"
	]

	def full_name 
		return "#{self.last_name}, #{self.first_name}"
	end 

	def set_role
		self.role_id = 1
		self.home_store_id = 0
	end 


end

bullseyeScheduler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	before_filter :authorize
	helper_method :current_user	
	# Global API key for Target
	$key = 'Id8SS1KAXuFd2W7R60XC5AUTTGKbnU2U'

	def authorize
    redirect_to '/login' unless current_user
  end

	private 

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end


end

bullseyeScheduler/app/controllers/session_controller.rb
class SessionController < ApplicationController
	skip_before_filter :authorize	
	
 def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

bullseyeScheduler/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)
		@shift.store_id = current_user.home_store_id
		@shift.total = ((@shift.end - @shift.start) / 1.hour).round
    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
			@shift.total = ((@shift.end - @shift.start) / 1.hour).round
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

	# POST
	def takeShift
		@shift = Shift.find(params[:shift_id])
		@shift.user_id = current_user.id
		@shift.current_status = "Pending"
		@shift.save
		redirect_to root_url
	end 

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit!
    end
end

bullseyeScheduler/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
		@state = User::LOCATIONS
		if current_user.role.id != 1 
			@manShifts = Shift.where(current_status: "Pending").where(store_id: current_user.home_store_id)
		else 
			@manShifts = []
		end 
		@shifts = Shift.where(user_id: current_user.id)
		xml_content = Net::HTTP.get(URI.parse("http://api.target.com/v2/location/#{current_user.home_store_id}?key=#{$key}"))
		@data = Hash.from_xml(xml_content)		
  end

	def openShifts
		@shifts = Shift.where.not(user_id: current_user.id).where(current_status:"Open").where(store_id: current_user.home_store_id)
	end

  def about
  end

  def contact
  end
end

bullseyeScheduler/app/controllers/tracking_controller.rb
class TrackingController < ApplicationController

	def hours
		@user = current_user
	end 




end

bullseyeScheduler/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
	require 'open-uri'
	require 'net/http'

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
		@roles = Role.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
			@user.home_store_id = 0;
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	# GET
	def homestore
		xml_content = Net::HTTP.get(URI.parse("http://api.target.com/v2/location?adminarea=#{params[:location]}&key=#{$key}"))
		@data = Hash.from_xml(xml_content)		
	end
	# POST
	def sethomestore
		current_user.home_store_id = params[:store]
		current_user.save
		redirect_to '/'
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit!
    end
end

bullseyeScheduler/app/helpers/application_helper.rb
module ApplicationHelper
end

bullseyeScheduler/app/helpers/session_helper.rb
module SessionHelper
end

bullseyeScheduler/app/helpers/shifts_helper.rb
module ShiftsHelper
end

bullseyeScheduler/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bullseyeScheduler/app/helpers/tracking_helper.rb
module TrackingHelper
end

bullseyeScheduler/app/helpers/users_helper.rb
module UsersHelper
end

bullseyeScheduler/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bullseye Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
<body role="document">

  <!-- Fixed navbar -->
		<% if current_user %>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
					<%= link_to( "Bullseye Scheduler", root_url, :class => "navbar-brand" ) %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
						<% if current_user %>
							<% if current_user.role.id == 1 %> 
							<li><%= link_to "Log Out", logout_path %></li>
							<li><%= link_to "Edit Profile", "/users/#{current_user.id}/edit" %></li>
							<li><%= link_to "Find Open Shifts", static_pages_openShifts_path %></li>
							<li><%= link_to "Track My Hours", tracking_hours_path %></li>
							<% else %>
							<li><%= link_to "Log Out", logout_path %></li>
							<li><%= link_to "View Employees", users_path %></li>
							<li><%= link_to "Assign a Shift", new_shift_path %></li>
							<li><%= link_to "View Current Shifts", shifts_path %></li>
							<% end %>
						<% else %>
						<li><%# link_to "Log In", login_path %></li>
						<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
		<% end %>
		<div id="buffer">
		</div>
		<center>
		<div class="container-fluid">
		<% flash.each do |name, msg| %>
  			<%= content_tag :div, msg, :class => "alert alert-info" %>
		<% end %>
		</center>
		<div class="container theme-showcase" role="main">
			<%= yield %>
		</div>
						<% if current_user %>
		      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; MinneHack 2015</p>
        Haley Muotka<br>
        John Stupka<br>
        Gabe Jenson
      </footer>
			<% end %>
</body>
</html>

bullseyeScheduler/app/views/session/new.html.erb
<style>
body{
background-color: black;
}
</style>
	<center><%= image_tag "bullseye.png" %></center>
<div class="row">
	<div class="col-sm-4"></div>
	<div class="col-sm-4">
	<%= form_tag '/login' do %>
	
						<%= text_field_tag :email, nil, id: "email", type: "email", class: "form-control form-signin", placeholder: "Email Address"  %>
						<%= password_field_tag :password, nil, id: "inputPassword", type: "password", class: "form-control form-signin", placeholder: "Password" %>
						<%= submit_tag "Sign in", :class=>"btn btn-lg btn-danger btn-block" %>
	
	<% end %>
	</div>
	<div class="col-sm-4"></div>
</div>

bullseyeScheduler/app/views/shifts/_form.html.erb
	<%= form_for(@shift) do |f| %>
  	<% if @shift.errors.any? %>
    	<div id="error_explanation">
      	<h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      	<ul>
      		<% @shift.errors.full_messages.each do |message| %>
        		<li><%= message %></li>
      		<% end %>
      	</ul>
    	</div>
  	<% end %>
		<table class="table">
			<tr class="panel panel-danger field">
				<td class="panel-heading">
					<strong>Shift Date:</strong>
				</td>
				<td>
		    	<%= f.date_select :shift_date %>
				</td>
			</tr>
			<tr class="panel panel-danger field">
				<td class="panel-heading">
					<strong>Start:</strong>
				</td>
				<td>
					<%= f.time_select :start , :minute_step => 15%>
  			</td>
			</tr>
			<tr class="panel panel-danger field">
				<td class="panel-heading">
					<strong>End:</strong>
				</td>
				<td>
					<%= f.time_select :end , :minute_step => 15%>
				</td>
			</tr>
			<tr class="panel panel-danger field">
					<td class="panel-heading">
						<strong>Employee:</strong>
					</td>
					<td>
						<%= f.select :user_id, options_for_select(User.all.map{|x| [x.first_name, x.id] }) %>
					</td>
			</tr>
			<tr class="panel panel-danger field">
					<td class="panel-heading">
						<strong>Status:</strong>
					</td>
					<td>
						<%= f.select :current_status, options_for_select(Shift::STATUS.map{|x| x }) %>
					</td>
			</tr>
	</table>
<%= submit_tag "Submit Shift", :class=>"btn btn-default" %>
<% end %> 

bullseyeScheduler/app/views/shifts/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<h1 class="panel-title">Editing Shift</h1>
</div>

<%= render 'form' %>
<br>
<div class="actions">
<%= link_to 'Show Shift', @shift, :class=>"btn btn-default" %>
<%= link_to 'Previous Page', shifts_path, :class=>"btn btn-default" %>
</div>

bullseyeScheduler/app/views/shifts/index.html.erb
<h1>View All Current Shifts</h1>

<table class="table">
  <thead class="panel panel-danger">
    <tr class="panel-heading">
      <th>Date</th>
      <th>Start</th>
      <th>End</th>
      <th>Total Hours</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.shift_date %></td>
        <td><%= shift.start.strftime('%H:%M') %></td>
        <td><%= shift.end.strftime('%H:%M') %></td>
        <td><%= shift.total %></td>
        <td><%= User.find(shift.user_id).full_name %></td>
        <td><%= link_to 'Show Shift', shift, :class=>"btn btn-default" %></td>
        <td><%= link_to 'Edit Shift', edit_shift_path(shift), :class=>"btn btn-default" %></td>
        <td><%= button_to 'Remove', shift, method: :delete, :onclick => "return confirm('Are you sure you want to delete this Shift?')", :class=>"btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path, :class=>"btn btn-default" %>

bullseyeScheduler/app/views/shifts/new.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<h1 class="panel-title">New Shift</h1>
</div>
<div class="panel-body">
<%= render 'form' %>

<%= link_to 'Previous Page', shifts_path %>

</div>

bullseyeScheduler/app/views/shifts/show.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1 class="panel-title">View Shift - #<%= @shift.id %></h1>
	</div>
	<div class="panel-body">
	<table class="table">
	<tr class="panel panel-danger">
		<td class="panel-heading">
			<strong>Date:</strong>
		</td>
		<td>
			<%= @shift.shift_date %>
		</td>
	</tr>

	<tr class="panel panel-danger">
		<td class="panel-heading">
			<strong>Start:</strong>
		</td>
		<td>
			<%= @shift.start.strftime('%H:%M') %>
		</td>
	</tr>
	<tr class="panel panel-danger">
		<td class="panel-heading">
			<strong>End:</strong>
		</td>
		<td>
			<%= @shift.end.strftime('%H:%M') %>
		</td>
	</tr>
	<tr class="panel panel-danger">
		<td class="panel-heading">
				<strong>Total:</strong>
		</td>
		<td>
			<%= @shift.total %>
		</td>
	</tr>
	<tr class="panel panel-danger">
		<td class="panel-heading">
			<strong>User:</strong>
		</td>
		<td>
			<%= User.find(@shift.user_id).full_name %>
		</td>
	<tr class="panel panel-danger">
		<td class="panel-heading">
			<strong>Status:</strong>
		</td>
		<td>
			<%= @shift.current_status %>
		</td>
	</table>

<%= link_to 'Edit Shift', edit_shift_path(@shift), :class=>"btn btn-default" %>
<%= link_to 'Previous Page', shifts_path, :class=>"btn btn-default" %>
</div>
</div>

bullseyeScheduler/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bullseyeScheduler/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

bullseyeScheduler/app/views/static_pages/index.html.erb
<div class="row">
	<div class="col-sm-6">
		<h1>Welcome - <%= current_user.first_name %> <%= current_user.last_name%></h1>
	</div>
	<div class="col-sm-6">
		<% if current_user.role == nil %> 
		<h1>Role: N/A</h1>
		<% else %>
		<h1>Role:<%= Role.find(current_user.role).name %></h1>
		<% end %>
	</div>
</div>
<hr> 

<div class="row">
	<div class="col-sm-6 well">
		<h3>Your Shifts - <%= @shifts.length %></h3>
		<hr>
		<% if @shifts.length <= 0 %> 
			<h5 class="alert alert-danger">No Shifts Found</h5> 
		<% else %> 
				<% @shifts.each do |shift| %>
						<% if shift.current_status == "General" %>
						<div class= "text-success">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Open" %>
						<div class= "text-primary">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Pending" %>
						<div class= "text-warning">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Closed" %>
						<div class= "text-danger">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Finalized" %>
						<div>
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% end %>
						</div>
						<br />
				<% end %> 
		<% end %> 

	</div>
	<div class="col-sm-6 well">
		<h3>Home Store</h3>
		<hr>
		<% if current_user.home_store_id == nil || current_user.home_store_id == 0 %> 
			<h5 class="alert alert-danger">No Home Store Set</h5> 
		<% else %> 
			<h5><%= @data["Location"]["Name"] %></h5>
			<u>Address</u>
			<br>
			<%= @data["Location"]["Address"]["FormattedAddress"] %>
			<br>
			<u>Phone</u>
			<br>
			<% if @data["Location"]["TelephoneNumber"].kind_of?(Array)%>
				<%= @data["Location"]["TelephoneNumber"] ? @data["Location"]["TelephoneNumber"].first["PhoneNumber"] : "N/A" %>
			<% else %> 
				<%= @data["Location"]["TelephoneNumber"] ? @data["Location"]["TelephoneNumber"]["PhoneNumber"] : "N/A" %>
			<% end %>
		<% end %>
		<p>
		 	<div class="btn-group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Choose HomeStore</button>
			  <ul class="dropdown-menu scrollable-menu" role="menu">
					<% @state.each do |s| %> 
						<li><%= link_to s,"/users/#{current_user.id}/home/#{s}" %> </li>
					<% end %> 
				</ul>
		</div>
		</p>
</div>
</div>
<% if current_user.role.id != 1 %> 
<div class="row">
	<div class="col-sm-12 well">
		<h3>Manage Store Shifts - <%= @manShifts.length %></h3>
		<hr>
		<% if @manShifts.length <= 0 %> 
			<h5 class="alert alert-danger">No Shifts Found</h5> 
		<% else %> 
				<% @manShifts.each do |shift| %>
						<% if shift.current_status == "General" %>
						<div class= "text-success">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Open" %>
						<div class= "text-primary">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Pending" %>
						<div class= "text-warning">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Closed" %>
						<div class= "text-danger">
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% elsif shift.current_status == "Finalized" %>
						<div>
						<%= link_to "#{shift.shift_date.strftime('%F')}			#{shift.start.strftime('%H:%M')}-#{shift.end.strftime('%H:%M')}", "/shifts/#{shift.id}" %>
						<br/>Current Status: <%= shift.current_status %> 
						<% end %>
						</div>
						<br />
				<% end %> 
		<% end %> 

	</div>
</div>
<% end %>

bullseyeScheduler/app/views/users/homestore.html.erb
<h1>Please Select Your HomeStore</h1>
<hr>
<div class="row">
	<% @data["Locations"]["Location"].each do |store| %>
	<div class="col-sm-4">
		<h3><%= store["Name"] %> </h3>
		<h4><%= store["Address"]["AddressLine1"] %> </h4>
		<h4><%= store["Address"]["City"] %> </h4>
		<%= link_to "Select Store", "/users/#{current_user.id}/setstore?"+{store:"#{store["ID"]}"}.to_param, class:"btn btn-lg btn-danger" %>
	</div>
	
	<% end %>
</div>

bullseyeScheduler/app/views/users/index.html.erb
<h1>Listing Employees</h1>

<table class="table">
  <thead class="panel panel-danger">
    <tr class="panel-heading">
			<th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
				<td><%= user.first_name %> <%= user.middle_name %> <%= user.last_name %></td>
        <td><%= user.email %> </td>
        <td><%= link_to 'User Profile', user, :class=>"btn btn-default" %> </td>
        <td><%= link_to 'Edit User', edit_user_path(user), :class=>"btn btn-default" %></td>
        <td><%= button_to 'Delete', user, method: :delete, :onclick => "return confirm('Are you sure you want to delete this Employee?')", :class=>"btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, :class=>"btn btn-default" %>

bullseyeScheduler/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

bullseyeScheduler/app/views/users/show.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<h1 class="panel-title">User Profile</h1>
</div>

<div class="panel-body">
	<table class="table">
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>Name:</strong>
			</td>
			<td>
				<%= @user.first_name %> <%= @user.middle_name %> <%= @user.last_name %>
			</td>	
		</tr>
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>Email Address:</strong>
			</td>
			<td>
				<%= @user.email %>
			</td>
		</tr>
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>Home Address:</strong>
			</td>
			<td>
				<%= @user.home_address %>
			</td>
		</tr>
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>Role:</strong>
			</td>
			<td>
				<%= Role.find(@user.role_id).name %>
			</td>
		</tr>
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>HomeStore:</strong>
			</td>
			<td>
			<% if @user.home_store_id == 0 %>
				N/A
			<% else %>
				<%= Hash.from_xml(Net::HTTP.get(URI.parse("http://api.target.com/v2/location/#{@user.home_store_id}?key=#{$key}")))["Location"]["Name"] %> 
			<% end %>
		</tr>
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>
					Created at:
				</strong>
			</td>
			<td>
				<%= @user.created_at %>
			</td>
		</tr>
		<tr class="panel panel-danger">
			<td class="panel-heading">
				<strong>
					Updated at:
				</strong>
			</td>
			<td>
				<%= @user.updated_at %>
			</td>
		</tr>
	</table>
<%= link_to 'Edit User', edit_user_path(@user), :class=>"btn btn-default" %>
<%= link_to 'Previous Page', users_path, :class=>"btn btn-default" %>
</div>
</div>